# Generated by Django 4.2.7 on 2023-12-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='content',
        ),
    ]
