# Generated by Django 4.2.7 on 2023-12-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_comment_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
